//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoSurge.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfoSurge.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дължината на въведението на новината трябва да е между {2} и {1} символа дълго!.
        /// </summary>
        internal static string ArticleContentLengthMessage {
            get {
                return ResourceManager.GetString("ArticleContentLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведението на новината е задължително!.
        /// </summary>
        internal static string ArticleContentRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ArticleContentRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дължината на въведението на новината трябва да е между {2} и {1} символа дълго!.
        /// </summary>
        internal static string ArticleIntroductionLengthMessage {
            get {
                return ResourceManager.GetString("ArticleIntroductionLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Въведението на новината е задължително!.
        /// </summary>
        internal static string ArticleIntroductionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ArticleIntroductionRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Основното изображение е задължително!.
        /// </summary>
        internal static string ArticleMainImageErrorMessage {
            get {
                return ResourceManager.GetString("ArticleMainImageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дължината на заглавието на новината трябва да е между {2} и {1} символа дълго!.
        /// </summary>
        internal static string ArticleTitleLengthMessage {
            get {
                return ResourceManager.GetString("ArticleTitleLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавието на новината е задължително!.
        /// </summary>
        internal static string ArticleTitleRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ArticleTitleRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дължината на описанието на категория трябва да е между {2} и {1} символа дълго!.
        /// </summary>
        internal static string CategoryDescriptionLengthMessage {
            get {
                return ResourceManager.GetString("CategoryDescriptionLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описанието на категорията е задължително!.
        /// </summary>
        internal static string CategoryDescriptionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CategoryDescriptionRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дължината на името на категория трябва да е между {2} и {1} символа дълго!.
        /// </summary>
        internal static string CategoryNameLengthMessage {
            get {
                return ResourceManager.GetString("CategoryNameLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Името на категорията е задължително!.
        /// </summary>
        internal static string CategoryNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CategoryNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дължината на съдържанието на коментара трябва да е между {2} и {1} символа дълго!.
        /// </summary>
        internal static string CommentContentLengthMessage {
            get {
                return ResourceManager.GetString("CommentContentLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Съдържанието на коментара е задължително!.
        /// </summary>
        internal static string CommentContentRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CommentContentRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дължината на заглавието на коментара трябва да е между {2} и {1} символа дълго!.
        /// </summary>
        internal static string CommentTitleLengthMessage {
            get {
                return ResourceManager.GetString("CommentTitleLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заглавието на коментара е задължително!.
        /// </summary>
        internal static string CommentTitleRequiredErrorMessage {
            get {
                return ResourceManager.GetString("CommentTitleRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейл адреса не е в правилния формат, моля опитайте отново (формат: &apos;example@example.com&apos;)!.
        /// </summary>
        internal static string UserEmailInvalidErrorMessage {
            get {
                return ResourceManager.GetString("UserEmailInvalidErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имейл адреса е задължителен!.
        /// </summary>
        internal static string UserEmailRequiredErrorMessage {
            get {
                return ResourceManager.GetString("UserEmailRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дължината на името на потребителя трябва да е между {2} и {1} символа дълго!.
        /// </summary>
        internal static string UserFirstNameLengthMessage {
            get {
                return ResourceManager.GetString("UserFirstNameLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Името на потребителя е задължително!.
        /// </summary>
        internal static string UserFirstNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("UserFirstNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дължината на фамилията на потребителя трябва да е между {2} и {1} символа дълго!.
        /// </summary>
        internal static string UserLastNameLengthMessage {
            get {
                return ResourceManager.GetString("UserLastNameLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилията на потребителя е задължителна!.
        /// </summary>
        internal static string UserLastNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("UserLastNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дължината на потребителското име трябва да е между {2} и {1} символа дълго!.
        /// </summary>
        internal static string UserNameLengthMessage {
            get {
                return ResourceManager.GetString("UserNameLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Потребителското име е задължително!.
        /// </summary>
        internal static string UserNameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("UserNameRequiredErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дължината на паролата трябва да е между {2} и {1} символа дълго!.
        /// </summary>
        internal static string UserPasswordLengthMessage {
            get {
                return ResourceManager.GetString("UserPasswordLengthMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролите не съвпадат!.
        /// </summary>
        internal static string UserPasswordNotMatchErrorMessage {
            get {
                return ResourceManager.GetString("UserPasswordNotMatchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролата е задължителна!.
        /// </summary>
        internal static string UserPasswordRequiredErrorMessage {
            get {
                return ResourceManager.GetString("UserPasswordRequiredErrorMessage", resourceCulture);
            }
        }
    }
}
